# IT Company Employee Data

#### TASK-1 : The company has hired 30 candidates recently assign to employee ids to these 30 candidates as per details below save the employee ids in separate 1D arrays, one for each department, and print them

In [1]:
import numpy as np
HR = np.arange(1,4)
HR

array([1, 2, 3])

In [3]:
IT = np.arange(4,19)
IT

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [5]:
Finance = np.arange(19,24)
Finance

array([19, 20, 21, 22, 23])

In [6]:
Sales = np.arange(24,31)
Sales

array([24, 25, 26, 27, 28, 29, 30])

##### 

#### TASK-2 : Create four different 1D arrays to hold only the salaries of the employees as per the details below and print them.

In [8]:
HR_SAL = [50,60,57]
HR_sal = np.array([HR_SAL])
HR_sal

array([[50, 60, 57]])

In [24]:
IT_sal = np.full(15,67)
IT_sal

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [10]:
Fin_sal = [60,65,50,70,87]
Finance_sal = np.array([Fin_sal])
Finance_sal

array([[60, 65, 50, 70, 87]])

In [11]:
sales_sal = [50,60,65,90,56,65,71]
Sales_sal = np.array([sales_sal])
Sales_sal

array([[50, 60, 65, 90, 56, 65, 71]])

#### 

#### TASK-3 : Calculate the department wise average salary expenses on the 30 employees. also determine the departments with the highest average salary expenses on the employees.

In [12]:
AVG_HR = np.mean(HR_sal)
AVG_HR

55.666666666666664

In [25]:
AVG_IT = np.mean(IT_sal)
AVG_IT

67.0

In [14]:
AVG_FINANCE = np.mean(Finance_sal)
AVG_FINANCE

66.4

In [15]:
AVG_SALES = np.mean(Sales_sal)
AVG_SALES

65.28571428571429

### Interpretation : The IT department have the highest average salary expenses on the employees i.e., 67.0 thousand dollars.

#### 

#### TASK-4 : List the highest salaries in the HR and Finance departments.

In [16]:
High_HR = np.max(HR_sal)
High_HR

60

### Highest salary in HR department is 60 thousand dollars.

In [18]:
High_Finance = np.max(Finance_sal)
High_Finance

87

### Highest salary in Finance department is 87 thousand dollars.

### 

#### TASK-5 : The company has decided to give a joining/signing bonus worth 5% of the gross salary to those employees whose employees who belong to IT department. update the salary of such employees after adding the bonus. display the updated salary.

In [26]:
IT_sal

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [41]:
Updated_salary = IT_sal+(IT_sal*5/100)
Updated_salary

array([70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35,
       70.35, 70.35, 70.35, 70.35, 70.35, 70.35])

#### 