# Online shopping/E-Commerce Data Analysis 

In [1]:
import numpy as np
import os
os.getcwd()

'C:\\Users\\SHUBH\\Downloads'

In [2]:
com_data = np.genfromtxt("DS1_C4_S1_Shopping_Data_Challenge.csv",delimiter=",",skip_header = 1, dtype="int")
com_data

array([[  1,  19,  15,  39],
       [  2,  21,  15,  81],
       [  3,  20,  16,   6],
       [  4,  23,  16,  77],
       [  5,  31,  17,  40],
       [  6,  22,  17,  76],
       [  7,  35,  18,   6],
       [  8,  23,  18,  94],
       [  9,  64,  19,   3],
       [ 10,  30,  19,  72],
       [ 11,  67,  19,  14],
       [ 12,  35,  19,  99],
       [ 13,  58,  20,  15],
       [ 14,  24,  20,  77],
       [ 15,  37,  20,  13],
       [ 16,  22,  20,  79],
       [ 17,  35,  21,  35],
       [ 18,  20,  21,  66],
       [ 19,  52,  23,  29],
       [ 20,  35,  23,  98],
       [ 21,  35,  24,  35],
       [ 22,  25,  24,  73],
       [ 23,  46,  25,   5],
       [ 24,  31,  25,  73],
       [ 25,  54,  28,  14],
       [ 26,  29,  28,  82],
       [ 27,  45,  28,  32],
       [ 28,  35,  28,  61],
       [ 29,  40,  29,  31],
       [ 30,  23,  29,  87],
       [ 31,  60,  30,   4],
       [ 32,  21,  30,  73],
       [ 33,  53,  33,   4],
       [ 34,  18,  33,  92],
       [ 35,  

### 

#### TASK-1 : Display the details of the customers whose spending score is greater then 80. also, display the total count of these customers.

In [10]:
index = np.where(com_data[:,3] > 80)
Cust = com_data[:,:][index]
print("Customer details whose soending score is greater than 80: \n",Cust)
print()
print("Count of customers: ",Cust[:,1].size)

Customer details whose soending score is greater than 80: 
 [[  2  21  15  81]
 [  8  23  18  94]
 [ 12  35  19  99]
 [ 20  35  23  98]
 [ 26  29  28  82]
 [ 30  23  29  87]
 [ 34  18  33  92]
 [ 36  21  33  81]
 [ 42  24  38  92]
 [124  39  69  91]
 [128  40  71  95]
 [136  29  73  88]
 [142  32  75  93]
 [144  32  76  87]
 [146  28  77  97]
 [150  34  78  90]
 [152  39  78  88]
 [156  27  78  89]
 [162  29  79  83]
 [164  31  81  93]
 [168  33  86  95]
 [174  36  87  92]
 [176  30  88  86]
 [180  35  93  90]
 [182  32  97  86]
 [184  29  98  88]
 [186  30  99  97]
 [190  36 103  85]
 [194  38 113  91]
 [200  30 137  83]]

Count of customers:  30


### 

#### TASK-2 : Extract and display the data of the customers who are 20 to 24 years of age.

In [14]:
index1 = np.where((com_data[:,1] >=20) & (com_data[:,1] <=24))
age_data = com_data[:,:][index1]
print("Customers who have 20 to 24 years of age: \n",age_data)

Customers who have 20 to 24 years of age: 
 [[  2  21  15  81]
 [  3  20  16   6]
 [  4  23  16  77]
 [  6  22  17  76]
 [  8  23  18  94]
 [ 14  24  20  77]
 [ 16  22  20  79]
 [ 18  20  21  66]
 [ 30  23  29  87]
 [ 32  21  30  73]
 [ 36  21  33  81]
 [ 40  20  37  75]
 [ 42  24  38  92]
 [ 46  24  39  65]
 [ 79  23  54  52]
 [ 85  21  54  57]
 [ 88  22  57  55]
 [ 96  24  60  52]
 [100  20  61  49]
 [101  23  62  41]
 [106  21  62  42]
 [125  23  70  29]
 [135  20  73   5]]


### 

#### TASK-3 : Display the IDs of the customers with the lowest annual income(s) and the highest annual income.

In [32]:
lowest = np.min(com_data[:,2])
index2 = np.where(com_data[:,2]==[lowest])
lowest_income = com_data[:,:][index2]
highest = np.max(com_data[:,2])
index3 = np.where(com_data[:,2]==[highest])
highest_income = com_data[:,:][index3]
print("Customers with Lowest annual Income: \n",lowest_income)
print()
print("Customers with Highest annual Income: \n",highest_income)

Customers with Lowest annual Income: 
 [[ 1 19 15 39]
 [ 2 21 15 81]]

Customers with Highest annual Income: 
 [[199  32 137  18]
 [200  30 137  83]]


### 

#### TASK-4 : Display the details of the  customers who are less than 45 years of age, have an annual income greater than 35K, and have a spending score greater than 75. how many such customers are there in the given data?

In [38]:
index4 = np.where((com_data[:,1] < 45) & (com_data[:,2] >35) & (com_data[:,3] >75))
customer = com_data[:,:][index4]
print("Details of Customers: \n",customer)
print()
print("Number of students: ",customer[:,1].size)

Details of Customers: 
 [[ 42  24  38  92]
 [124  39  69  91]
 [126  31  70  77]
 [128  40  71  95]
 [136  29  73  88]
 [142  32  75  93]
 [144  32  76  87]
 [146  28  77  97]
 [150  34  78  90]
 [152  39  78  88]
 [154  38  78  76]
 [156  27  78  89]
 [158  30  78  78]
 [162  29  79  83]
 [164  31  81  93]
 [168  33  86  95]
 [174  36  87  92]
 [176  30  88  86]
 [180  35  93  90]
 [182  32  97  86]
 [184  29  98  88]
 [186  30  99  97]
 [190  36 103  85]
 [194  38 113  91]
 [196  35 120  79]
 [200  30 137  83]]

Number of students:  26


### 

#### TASK-5 : During the christmas season, the company wishes to offer random gift coupons valued between 10 and 50 to aall its customers. Add a new column for the gift coupons in existing data. Display the details of customers after adding the new coloumn

In [50]:
com_data[:,1].size

200

In [54]:
a = np.random.randint(10,51,200)
new_com_data = np.append(com_data, a.reshape(-1,1), axis=1)
print("Details of customers after adding the new coloumn: \n",new_com_data)

Details of customers after adding the new coloumn: 
 [[  1  19  15  39  32]
 [  2  21  15  81  10]
 [  3  20  16   6  42]
 [  4  23  16  77  29]
 [  5  31  17  40  13]
 [  6  22  17  76  24]
 [  7  35  18   6  39]
 [  8  23  18  94  30]
 [  9  64  19   3  45]
 [ 10  30  19  72  18]
 [ 11  67  19  14  38]
 [ 12  35  19  99  25]
 [ 13  58  20  15  20]
 [ 14  24  20  77  44]
 [ 15  37  20  13  46]
 [ 16  22  20  79  20]
 [ 17  35  21  35  44]
 [ 18  20  21  66  32]
 [ 19  52  23  29  15]
 [ 20  35  23  98  16]
 [ 21  35  24  35  44]
 [ 22  25  24  73  34]
 [ 23  46  25   5  30]
 [ 24  31  25  73  10]
 [ 25  54  28  14  33]
 [ 26  29  28  82  45]
 [ 27  45  28  32  14]
 [ 28  35  28  61  34]
 [ 29  40  29  31  12]
 [ 30  23  29  87  22]
 [ 31  60  30   4  45]
 [ 32  21  30  73  47]
 [ 33  53  33   4  30]
 [ 34  18  33  92  32]
 [ 35  49  33  14  34]
 [ 36  21  33  81  17]
 [ 37  42  34  17  15]
 [ 38  30  34  73  44]
 [ 39  36  37  26  44]
 [ 40  20  37  75  36]
 [ 41  65  38  35  29]
 [ 4

In [55]:
com_data.size

800

In [56]:
new_com_data.size

1000